package repo

import (
	"reflect"
	"sort"
	"testing"
	"testing/fstest"
)

func TestLooksGenerated(t *testing.T) {
	yes := []struct {
		name, body string
	}{
		{"go banner", "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage pb\n"},
		{"go banner lowercased anchors", "// code generated by mockgen. do not edit.\n"},
		{"client-go style", "// Code generated by client-gen. DO NOT EDIT.\n\npackage v1\n"},
		{"at-generated tag", "/* @generated by thrift */\nstruct X {}\n"},
		{"generated by + do not edit split lines", "# Generated by the protocol buffer compiler.\n# DO NOT EDIT!\n"},
		{"auto-generated", "// This file is auto-generated. DO NOT EDIT.\n"},
	}
	for _, c := range yes {
		if !looksGenerated([]byte(c.body)) {
			t.Errorf("%s: looksGenerated = false, want true", c.name)
		}
	}

	no := []struct {
		name, body string
	}{
		{"plain source", "package main\n\nfunc main() {}\n"},
		{"do-not-edit prose without generated", "// Config file. DO NOT EDIT below this line by hand.\nport = 8080\n"},
		{"mentions generated deep, no marker", "package x\n// this parser handles generated columns in SQL\nfunc f() {}\n"},
		{"generated word alone", "// generator utilities\npackage gen\n"},
	}
	for _, c := range no {
		if looksGenerated([]byte(c.body)) {
			t.Errorf("%s: looksGenerated = true, want false (false positive)", c.name)
		}
	}
}

// TestLooksGenerated_HeadBounded confirms a marker past the scanned head window
// does NOT trip the sniff (banners live at the very top).
func TestLooksGenerated_HeadBounded(t *testing.T) {
	filler := make([]byte, generatedHeadBytes+100)
	for i := range filler {
		filler[i] = 'x'
	}
	body := append(filler, []byte("\n// Code generated. DO NOT EDIT.\n")...)
	if looksGenerated(body) {
		t.Error("a marker past generatedHeadBytes should not be detected")
	}
}

// TestWalkFS_SkipGenerated covers the opt-in KEN_SKIP_GENERATED filter: default
// OFF keeps a generated-header file; on skips it; ordinary source is unaffected
// either way.
func TestWalkFS_SkipGenerated(t *testing.T) {
	base := fstest.MapFS{
		"zz_generated.deepcopy.go": {Data: []byte("// Code generated by deepcopy-gen. DO NOT EDIT.\n\npackage v1\n\nfunc (in *T) DeepCopy() {}\n")},
		"handwritten.go":           {Data: []byte("package v1\n\nfunc Real() int { return 1 }\n")},
	}

	t.Run("default OFF: generated file is kept", func(t *testing.T) {
		got, err := WalkFS(base, Options{})
		if err != nil {
			t.Fatalf("WalkFS: %v", err)
		}
		sort.Strings(got)
		want := []string{"handwritten.go", "zz_generated.deepcopy.go"}
		if !reflect.DeepEqual(got, want) {
			t.Errorf("default WalkFS = %v, want %v (generated kept when opt-in off)", got, want)
		}
	})

	t.Run("KEN_SKIP_GENERATED=1: generated file is skipped", func(t *testing.T) {
		t.Setenv("KEN_SKIP_GENERATED", "1")
		got, err := WalkFS(base, Options{})
		if err != nil {
			t.Fatalf("WalkFS: %v", err)
		}
		sort.Strings(got)
		want := []string{"handwritten.go"} // generated dropped
		if !reflect.DeepEqual(got, want) {
			t.Errorf("WalkFS = %v, want %v (generated skipped)", got, want)
		}
	})
}
